### ISSUE TITLE
[pypi] pip installation support

### ISSUE THREAD

**Issue by mythmgn** [baidu/CUP#19]

**Comment by mythmgn** [comment]
support pip installation

**Comment by mythmgn** [comment]
cup is ready for pypi installation. The only obstacle is name conflict. Waiting for pypi team to accept name retention request.

**Comment by cncert** [comment]
官方文档为何不考虑出个中文版的呢？这样就更受大家欢迎了

**Comment by mythmgn** [comment]
pipy  name rentation  https://github.com/pypa/warehouse/issues/4820 

is undergoing. Will push to pypi around middle of Nov.

**Comment by mythmgn** [comment]
> 官方文档为何不考虑出个中文版的呢？这样就更受大家欢迎了

@cncert 
http://cup.iobusy.com   官方版本相关的介绍在逐步增加中了, 欢迎take a look

**Comment by mythmgn** [comment]
[https://github.com/pavanmishra/cup/issues/2](url)

Many thanks to Mr Mishra. Cup will be released in pypi before March 1st.   The issue will be closed soon.

**Comment by mythmgn** [comment]
https://pypi.org/project/cup/ 

pypi package is available on pypi.   This issue will be closed after a while.

**Comment by mythmgn** [comment]
issue closed
