### ISSUE TITLE
Support Py3

### ISSUE THREAD

**Issue by mythmgn** [baidu/CUP#27]
**Is your feature request related to a problem? Please describe.**  
简洁描述下新feature的内容

Support py3

**Describe the solution you'd like**
描述下你想要什么样的解决方案

调研python3和python2区别， 并开启支持python3

**Describe alternatives you've considered**
是否有其他替代方案

**Additional context**
可以辅助其他人理解你的信息

**Comment by shuke163** [comment]
Please Support py3

**Comment by feiyx** [comment]
yes

**Comment by mythmgn** [comment]
py 3 will be supported before July (H1 of 2019).
