### ISSUE TITLE
cup.shell.async_run 执行耗时长达13s

### ISSUE THREAD

**Issue by liu0208xuan** [baidu/CUP#33]
**Describe the bug**    清晰简洁的BUG描述
cup.shell.async_run 执行耗时长达20s

**To Reproduce**   怎么去复现这个问题?

**Screenshots**  截图或者其他方式可以辅助其他人理解
截图是cup.res.linux.Process children 函数，基本时间消耗在这个部分：
![image](https://user-images.githubusercontent.com/15208795/57212523-93a27600-7016-11e9-82f3-c1cf18116674.png)

INFO:    2019-05-06 15:42:11,498 * [111144:139769870788352] [__init__.py:141] linux process instance inited
INFO:    2019-05-06 15:42:24,901 * [111144:139769870788352] [linux.py:661] process_num:1302

**Comment by mythmgn** [comment]
fixed ,  见文章分析: 
 http://blog.iobusy.com/%E7%9F%A5%E8%AF%86%E7%A7%AF%E7%B4%AF/Python%E8%B8%A9%E5%9D%91%E4%B9%8B%E6%97%85%E4%B9%8B1%E6%9D%80%E4%B8%8D%E6%AD%BB%E7%9A%84shell%E5%AD%90%E8%BF%9B%E7%A8%8B/

**Comment by mythmgn** [comment]
not a problem, closed
