### ISSUE TITLE
http://cup.iobusy.com 不能访问

### ISSUE THREAD

**Issue by fank-cd** [baidu/CUP#34]
http://cup.iobusy.com 不能访问

**Comment by mythmgn** [comment]
是不是 github 被墙了?   因为部门是用的 github page.    有时候也许会不稳定,  原因是你懂的哈

Regards,
Gallon (Guannan) Ma

---
https://github.com/baidu/CUP  (*C*ommon *U*seful *P*ython Lib's waiting for
you to discover)

**Comment by fank-cd** [comment]
果然是这个原因，谢谢

**Comment by mythmgn** [comment]
:)
