### ISSUE TITLE
安装3.0aplha时报错

### ISSUE THREAD

**Issue by IncubatorShokuhou** [baidu/CUP#38]
安装3.0aplha时报错。执行python3 setup.py install后出现以下信息：
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    __author__ = __import__(__name__).version.AUTHOR
  File "/mnt/test/CUP-3.0-alpha/cup/__init__.py", line 28, in <module>
    from cup import net
  File "/mnt/test/CUP-3.0-alpha/cup/net/__init__.py", line 20
    from cup.net import async
                            ^
SyntaxError: invalid syntax
None

**Comment by mythmgn** [comment]
环境信息 帮忙提供下 以及py的版本

[1] linux 发行版本 / kernel 版本

[2] py 版本

**Comment by WuyueniaLyumengzheng** [comment]
@mythmgn 
【1】Linux iZ2ze21r43b3icwd236v9jZ 3.10.0-957.5.1.el7.x86_64
【2】Python 3.7.3

**Comment by WuyueniaLyumengzheng** [comment]
尝试使用3.5版本python，安装成功。怀疑应该是3.7版本async成为关键词的缘故。

**Comment by mythmgn** [comment]
恩,  cup.net.async这个为了适配py3得改  在 release 里也说了, 这个暂时还不能用

**Comment by mythmgn** [comment]
async这个估计还需要些时日哈,  抱歉

**Comment by mythmgn** [comment]
async 的问题已解决 @IncubatorShokuhou
