### ISSUE TITLE
python3不兼容unicode

### ISSUE THREAD

**Issue by zsg555** [baidu/CUP#43]
```
#log.py
def _fail_handle(msg, e):
    if not isinstance(msg, unicode):
        msg = msg.decode('utf8')
    print('{0}\nerror:{1}'.format(msg, e))
```

**Comment by mythmgn** [comment]
@zsg555  请提供下你的运行环境信息 比如 mac os/ 还是 linux 还是啥,  和 python具体版本

thx

**Comment by mythmgn** [comment]
@zsg555  收到, 已fix.

**Comment by mythmgn** [comment]
https://github.com/baidu/CUP/commit/0fe89d7743f4b4aefed38c4ebd15725ada64f2cd

**Comment by mythmgn** [comment]
pip install -U cup 

版本3.2.20,  谢谢提供的py3兼容性问题线索

**Comment by wanmail** [comment]
还有其他几个地方,https://github.com/baidu/CUP/search?l=Python&q=unicode&type=code
