### ISSUE TITLE
`cup.shell.ShellExec().run` incompatible with python3.9 

### ISSUE THREAD

**Issue by endyul** [baidu/CUP#49]
**Describe the bug**    清晰简洁的BUG描述
```
File "/home/work/anaconda3/lib/python3.9/site-packages/cup/shell/oper.py", line 576, in run
    if cmdthd.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

Python3.9 removed `isAlive()` method from threading.Thread module, replaced by `is_alive()`.

**To Reproduce**   怎么去复现这个问题?

```
shelltool = cup.shell.ShellExec()

shelltool.run("echo hello", timeout=None)
```

**Screenshots**  截图或者其他方式可以辅助其他人理解

**Comment by mythmgn** [comment]
thx for the info. Enhancements have been merged into the master branch.

**Comment by mythmgn** [comment]
Uploading cup-3.2.28-py2.py3-none-any.whl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139k/139k [00:12<00:00, 10.9kB/s]

View at:
https://pypi.org/project/cup/3.2.28/

**Comment by mythmgn** [comment]
fixed, close issue
